name: Transmisión el9er

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  el9er:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update && sudo apt-get install -y ffmpeg rclone
      - run: |
          mkdir -p ~/.config/rclone
          cat <<EOF > ~/.config/rclone/rclone.conf
          [r2]
          type = s3
          provider = Other
          env_auth = false
          access_key_id = ${{ secrets.R2_ACCESS_KEY_ID }}
          secret_access_key = ${{ secrets.R2_SECRET_ACCESS_KEY }}
          endpoint = ${{ secrets.R2_ENDPOINT }}
          s3_force_path_style = true
          EOF
      - run: |
          mkdir -p /tmp/hls_el9er
          while true; do
            rclone copy /tmp/hls_el9er r2:${{ secrets.R2_BUCKET }}
            sleep 2
          done &
          ffmpeg -re -i "http://45.226.28.9:8085/Live/6fb1f0e7eb180cb1c37841fb3e8a163b/local-nuevelitoral_480.m3u8" \
            -c copy \
            -f hls -hls_time 4 -hls_list_size 6 \
            -hls_flags delete_segments /tmp/hls_el9er/el9er.m3u8
